# Site settings
title: telingc blog
email: 251240041@smail.nju.edu.cn
description: "To seek out and to understand is our way of living."
baseurl: ""
url: "http://telingc.github.io"
github_username:  telingc

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# giscus comments
giscus:
  repo: "telingc/telingc.github.io"
  repo_id: "R_kgDOT9Vqig"
  category: "Announcements"
  category_id: "DIC_kwDOT9Vqis4DDuHh"
  mapping: pathname
  input_position: top
  theme: dark
  lang: zh-CN
